name: Build
run-name: Build

on:
  - workflow_call

env:
  CARGO_TERM_COLOR: always

jobs:
  Build:
    strategy:
      matrix:
        os:
          - Ubuntu
          - Windows
          - MacOS
        version:
          - latest
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-${{ matrix.version }}
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release --verbose
      - name: Upload artifacts
        uses: actions/upload-artifact@v4.3.0
        with:
          name: miners-${{ matrix.os }}
          path: |
            target/release/main
            target/release/main.exe
