name: Check
run-name: Check

on:
  - workflow_call

env:
  CARGO_TERM_COLOR: always

jobs:
  Check:
    strategy:
      matrix:
        os: 
          - Ubuntu
        version:
          - latest
    name: Check on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-${{ matrix.version }}
    steps:
      - uses: actions/checkout@v4
      - name: Check
        run: cargo check --verbose
