name: Tag and Release
run-name: Tag and Release

on: workflow_call

jobs:
  Tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get next version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main
      - name: Tag
        run: git tag ${{ steps.semver.outputs.next }}
      - name: Update the Cargo.toml version
        run: sed -i '0,/version = "[^"]*"/s/version = "[^"]*"/version = "${{ steps.semver.outputs.nextStrict }}"/' Cargo.toml
      - name: Push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add . && git commit -m "Bump Cargo.toml version"
          git push && git push --tags
    outputs:
      current_tag: ${{ steps.semver.outputs.current }}
      next_tag: ${{ steps.semver.outputs.next }}
  Release:
    needs: [ tag ]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: miners-*
      - name: Rename executables
        run: |
          cd miners-ubuntu-latest
          mv main miners-ubuntu
          cd ../miners-macOS-latest
          mv main miners-macOS
          cd ../miners-windows-latest
          mv main.exe miners-windows.exe
          cd ../
      - name: Create draft release
        uses: ncipollo/release-action@v1.12.0
        with:
          prerelease: true
          draft: false
          commit: ${{ github.sha }}
          name: ${{ needs.tag.outputs.next_tag }}
          tag: ${{ needs.tag.outputs.next_tag }}
          body: '*Pending...*'
      - name: Update changelog
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ needs.tag.outputs.next_tag }}
          writeToFile: false
      - name: Update release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: miners-*/miners-*
          allowUpdates: true
          draft: false
          name: ${{ needs.tag.outputs.next_tag }}
          tag: ${{ needs.tag.outputs.next_tag }}
          body: |
            ${{ steps.changelog.outputs.changes }}

            **Full Changelog**: https://github.com/smellyshovel/miners/compare/${{ needs.tag.outputs.current_tag }}...${{ needs.tag.outputs.next_tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
