name: Test
run-name: Test

on:
  - workflow_call

env:
  CARGO_TERM_COLOR: always

jobs:
  Test:
    strategy:
      matrix:
        os:
          - Ubuntu
          - Windows
          - MacOS
        version:
          - latest
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-${{ matrix.version }}
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: cargo test --verbose
