name: Build
run-name: Build

on:
  - workflow_call

env:
  CARGO_TERM_COLOR: always

jobs:
  Build:
    strategy:
      matrix:
        os:
          - Ubuntu
          - Windows
          - MacOS
        version:
          - latest
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-${{ matrix.version }}
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release --verbose
