name: Check
run-name: Check

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  Check:
    strategy:
      matrix:
        os: 
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    name: Check on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Check
        run: cargo check --verbose
