name: Check, Test and Build
run-name: Check, Test and Build

on:
  push:
    branches-ignore:
      - main
  workflow_call:

jobs:
  Check:
    uses: ./.github/workflows/_check.yml
  Test:
    needs:
      - Check
    uses: ./.github/workflows/_test.yml
  Build:
    needs:
      - Check
    uses: ./.github/workflows/_build.yml