name: Check, Test and Build
run-name: Check, Test and Build

on:
  push:
    branches:
      - *
    branches-ignore:
      - main
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  Check:
    uses: ./.github/workflows/check.yml
  Test:
    needs:
      - Check
    uses: ./.github/workflows/test.yml
  Build:
    needs:
      - Check
    uses: ./.github/workflows/build.yml