name: Release
run-name: Release

on:
  push:
    branches:
      - main

jobs:
  Check-Test-and-Build:
    uses: ./.github/workflows/check-test-and-build.yml
  Tag-and-Release:
    uses: ./.github/workflows/tag_and_release.yml