name: Test, Build and Release

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: cargo test --verbose
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Build  
        run: cargo build --release --verbose
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.0
        with:
          name: miners-${{ matrix.os }}
          path: |
            target/release/main
            target/release/main.exe
  tag:
    needs: [test, build]
    name: Tag
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.semver.outputs.next }}
      changes: ${{ steps.changelog.outputs.changes }}
    steps:
      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}
      - uses: actions/checkout@v3
      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main
      - name: Tag  
        run: git tag ${{ steps.semver.outputs.next }}
      - name: Update Cargo.toml respectively
        run: sed -i '0,/version = "[^"]*"/s/version = "[^"]*"/version = "${{ steps.semver.outputs.nextStrict }}"/' Cargo.toml
      - name: Save changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add . && git commit -m "Bump Cargo.toml version"
          git push && git push --tags
  release:
    needs: [tag]
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: miners-*
      - name: Rename executables
        run: |
          cd miners-ubuntu-latest
          mv main miners-ubuntu
          cd ../miners-macOS-latest
          mv main miners-macOS
          cd ../miners-windows-latest
          mv main.exe miners-windows.exe
          cd ../
      - name: Create Draft Release
        uses: ncipollo/release-action@v1.12.0
        with:
          prerelease: true
          draft: false
          commit: ${{ github.sha }}
          name: ${{ steps.semver.outputs.next }}
          tag: ${{ steps.semver.outputs.next }}
          body: '*pending*'
      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.semver.outputs.next }}
          writeToFile: false

      - name: Update Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: miners-*/miners-*
          allowUpdates: true
          draft: false
          name: ${{ steps.semver.outputs.next }}
          tag: ${{ steps.semver.outputs.next }}
          body: |
            ## What's Changed :eyes:
    
            ${{ steps.changelog.outputs.changes }}
    
            **Full Changelog**: https://github.com/czernika/tailwindcss-grid-area/compare//${{ steps.semver.outputs.current }}...${{ steps.semver.outputs.next }}
          token: ${{ secrets.GITHUB_TOKEN }}
